version: 0.0
os: linux
files:
  - source: /
    destination: /app
hooks: 
  ApplicationStop:
    - location: tools/stop_server.sh
      timeout: 10
      runas: root
  ApplicationStart:
    - location: tools/start_server.sh
      timeout: 10
      runas: root

