version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "my_postgres"
    ports:
      - "5432:5432"
    volumes:
      - my_postgres1:/var/lib/postgresql/data
    environment: 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
#  web:
#    image: "python:3.9-slim"
#    container_name: "languagelearn_django"
#    ports:
#      - 
volumes:
  my_postgres1:
