AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  userPoolId:
    Type: String
    Description: User Pool ID associated with this project
Outputs:
  ChatQLApiId:
    Description: Unique AWS AppSync GraphQL API Identifier
    Value: !GetAtt chatQLApi.ApiId
  ChatQLApiUrl:
    Description: The Endpoint URL of your GraphQL API.
    Value: !GetAtt chatQLApi.GraphQLUrl
Resources:
  conversationsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
  messagesTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "conversationId"
          AttributeType: "S"
        -
          AttributeName: "createdAt"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "conversationId"
          KeyType: "HASH"
        -
          AttributeName: "createdAt"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
  userConversationsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "userId"
          AttributeType: "S"
        -
          AttributeName: "conversationId"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "userId"
          KeyType: "HASH"
        -
          AttributeName: "conversationId"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      GlobalSecondaryIndexes:
        -
          IndexName: "conversationId-index"
          KeySchema:
            -
              AttributeName: "conversationId"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"
          ProvisionedThroughput:
            ReadCapacityUnits: "5"
            WriteCapacityUnits: "5"
  usersTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
[      AttributeDefinitions:
        -
          AttributeName: "cognitoId"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "cognitoId"
          KeyType: "HASH"]
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"